DROP DATABASE IF EXISTS webinar;
CREATE DATABASE
IF NOT EXISTS webinar;
USE webinar;

CREATE TABLE
IF NOT EXISTS attendees
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  firstName VARCHAR
(45) NOT NULL,
lastName VARCHAR
(45) NOT NULL,
email VARCHAR
(45) NOT NULL UNIQUE,
country VARCHAR
(45) NOT NULL,
phone VARCHAR
(20) NOT NULL,
jobPosition VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(id)
)ENGINE = InnoDB;
